on:
    repository_dispatch:
        types: [echo]
jobs:
    echo:
        name: Echo
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: |
                  sleep 5
                  echo "${{github.event.client_payload.id}}"
